#ifndef ANALYSIS_H
#define ANALYSIS_H

#include "parser.h"

/**
 * Semantical analyser
 */
class Analyser {
    public:
        Analyser() = default;
        /**
         * Analyses the AST generated by the parser.
         * @return true or error, false on success.
         */
        bool analyse(StatementList *ast);
};

#endif  // ANALYSIS_H
