#ifndef ANALYSIS_H
#define ANALYSIS_H

#include "parser.h"

/**
 * Semantical analyser
 */
class Analyser {
    Parser parser;
    public:
        Analyser(Parser parser) : parser{parser} {}
        /**
         * Analyses the AST generated by the parser.
         * @return true or error, false on success.
         */
        bool analyse();
};

#endif  // ANALYSIS_H
